# Generated by Django 5.2.17 on 2026-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_billing_profile', '0003_provider_is_atypical_and_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerbillingprofile',
            name='is_atypical',
            field=models.BooleanField(default=False, help_text='True = atypical Colorado Medicaid provider without NPI. Uses medicaid_provider_id as NM109 with NM108=XX (never invent an NPI).'),
        ),
        migrations.AlterField(
            model_name='providerbillingprofile',
            name='npi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='providerbillingprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='EIN or TIN (digits only). Required for NPI providers in 837P REF*EI.', max_length=20, null=True),
        ),
    ]
