# Generated by Django 5.2.17 on 2026-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_billing_profile', '0004_sync_client_model_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_address_line_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_address_line_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='pay_to_zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
