# Generated by Django 5.2.17 on 2026-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_claim_status_edi_generated_and_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('DOCUMENTS_REQUIRED', 'Documents required'), ('DOCUMENTS_COMPLETE', 'Documents complete'), ('READY_FOR_837P', 'Ready for 837P'), ('EDI_GENERATED', '837P generated (pending upload)'), ('EDI_SENT', 'Uploaded to SFTP (awaiting HCPF pickup)'), ('EDI_ACCEPTED', '999/TA1 accepted by HCPF gateway'), ('EDI_REJECTED', '999/TA1 rejected — correction required'), ('ATTACHMENT_REQUIRED', 'Attachment required'), ('ATTACHMENT_QUEUED', 'Attachment queued'), ('ATTACHMENT_SUBMITTED', 'Attachment submitted'), ('ATTACHMENT_CONFIRMED', 'Attachment confirmed'), ('UNDER_REVIEW', 'Under review / adjudicating'), ('PAID', 'Paid'), ('DENIED', 'Denied')], default='DRAFT', max_length=32, null=True),
        ),
    ]
