from django.urls import path

from apps.edi.ack_views import (
    EDIAcknowledgementApplyAPIView,
    EDIAcknowledgementDetailAPIView,
    EDIAcknowledgementImport999APIView,
    EDIAcknowledgementListCreateAPIView,
)
from apps.edi.import_835_views import (
    EDI835ImportDetailAPIView,
    EDI835ImportListAPIView,
    EDI835ImportPollAPIView,
)
from apps.edi.import_277_views import EDIAcknowledgementImport277APIView
from apps.edi.import_277_poll_views import (
    EDI277ImportDetailAPIView,
    EDI277ImportListAPIView,
    EDI277ImportPollAPIView,
)
from apps.edi.import_999_views import (
    EDI999ImportDetailAPIView,
    EDI999ImportListAPIView,
    EDI999ImportPollAPIView,
)
from apps.edi.ops_999_diag_views import real_999_diag
from apps.edi.validation_report_views import (
    EDIValidationReportDetailAPIView,
    EDIValidationReportImportAPIView,
    EDIValidationReportListAPIView,
)
from apps.edi.remittance_views import (
    EDI835RemittanceDetailAPIView,
    EDI835RemittanceImportAPIView,
    EDI835RemittanceListAPIView,
)
from apps.edi.sftp_views import (
    SFTPCredentialsDetailAPIView,
    SFTPCredentialsListCreateAPIView,
    SFTPDirectoryDetailAPIView,
    SFTPDirectoryListCreateAPIView,
)
from apps.edi.views import (
    EDIControlNumberAllocateAPIView,
    EDIControlNumberDetailAPIView,
    EDIControlNumberListCreateAPIView,
    EDIFileDetailAPIView,
    EDIFileFromBatchAPIView,
    EDIFileGenerate837PAPIView,
    EDIFileListCreateAPIView,
    EDIFileMarkUploadedAPIView,
    EDIFileQueueUploadAPIView,
    EDIFileTransferLogDetailAPIView,
    EDIFileTransferLogListAPIView,
)

urlpatterns = [
    path("ops/real-999-diag/", real_999_diag, name="ops-real-999-diag"),
    path(
        "edi-control-numbers/",
        EDIControlNumberListCreateAPIView.as_view(),
        name="edi-control-number-list-create",
    ),
    path(
        "edi-control-numbers/allocate/",
        EDIControlNumberAllocateAPIView.as_view(),
        name="edi-control-number-allocate",
    ),
    path(
        "edi-control-numbers/<int:pk>/",
        EDIControlNumberDetailAPIView.as_view(),
        name="edi-control-number-detail",
    ),
    path(
        "edi-files/",
        EDIFileListCreateAPIView.as_view(),
        name="edi-file-list-create",
    ),
    path(
        "edi-files/from-batch/",
        EDIFileFromBatchAPIView.as_view(),
        name="edi-file-from-batch",
    ),
    path(
        "edi-files/generate-837p/",
        EDIFileGenerate837PAPIView.as_view(),
        name="edi-file-generate-837p",
    ),
    path(
        "edi-files/<int:pk>/mark-uploaded/",
        EDIFileMarkUploadedAPIView.as_view(),
        name="edi-file-mark-uploaded",
    ),
    path(
        "edi-files/<int:pk>/upload/",
        EDIFileQueueUploadAPIView.as_view(),
        name="edi-file-queue-upload",
    ),
    path(
        "edi-files/<int:pk>/",
        EDIFileDetailAPIView.as_view(),
        name="edi-file-detail",
    ),
    path(
        "edi-file-transfer-logs/",
        EDIFileTransferLogListAPIView.as_view(),
        name="edi-file-transfer-log-list",
    ),
    path(
        "edi-file-transfer-logs/<int:pk>/",
        EDIFileTransferLogDetailAPIView.as_view(),
        name="edi-file-transfer-log-detail",
    ),
    path(
        "edi-acknowledgements/",
        EDIAcknowledgementListCreateAPIView.as_view(),
        name="edi-acknowledgement-list-create",
    ),
    path(
        "edi-acknowledgements/apply/",
        EDIAcknowledgementApplyAPIView.as_view(),
        name="edi-acknowledgement-apply",
    ),
    path(
        "edi-acknowledgements/import-999/",
        EDIAcknowledgementImport999APIView.as_view(),
        name="edi-acknowledgement-import-999",
    ),
    path(
        "edi-acknowledgements/import-277/",
        EDIAcknowledgementImport277APIView.as_view(),
        name="edi-acknowledgement-import-277",
    ),
    path(
        "edi-277-imports/",
        EDI277ImportListAPIView.as_view(),
        name="edi-277-import-list",
    ),
    path(
        "edi-277-imports/poll/",
        EDI277ImportPollAPIView.as_view(),
        name="edi-277-import-poll",
    ),
    path(
        "edi-277-imports/<int:pk>/",
        EDI277ImportDetailAPIView.as_view(),
        name="edi-277-import-detail",
    ),
    path(
        "edi-validation-reports/",
        EDIValidationReportListAPIView.as_view(),
        name="edi-validation-report-list",
    ),
    path(
        "edi-validation-reports/import/",
        EDIValidationReportImportAPIView.as_view(),
        name="edi-validation-report-import",
    ),
    path(
        "edi-validation-reports/<int:pk>/",
        EDIValidationReportDetailAPIView.as_view(),
        name="edi-validation-report-detail",
    ),
    path(
        "edi-835-remittances/",
        EDI835RemittanceListAPIView.as_view(),
        name="edi-835-remittance-list",
    ),
    path(
        "edi-835-remittances/import/",
        EDI835RemittanceImportAPIView.as_view(),
        name="edi-835-remittance-import",
    ),
    path(
        "edi-835-remittances/<int:pk>/",
        EDI835RemittanceDetailAPIView.as_view(),
        name="edi-835-remittance-detail",
    ),
    path(
        "edi-835-imports/",
        EDI835ImportListAPIView.as_view(),
        name="edi-835-import-list",
    ),
    path(
        "edi-835-imports/poll/",
        EDI835ImportPollAPIView.as_view(),
        name="edi-835-import-poll",
    ),
    path(
        "edi-835-imports/<int:pk>/",
        EDI835ImportDetailAPIView.as_view(),
        name="edi-835-import-detail",
    ),
    path(
        "edi-acknowledgements/<int:pk>/",
        EDIAcknowledgementDetailAPIView.as_view(),
        name="edi-acknowledgement-detail",
    ),
    path(
        "edi-999-imports/",
        EDI999ImportListAPIView.as_view(),
        name="edi-999-import-list",
    ),
    path(
        "edi-999-imports/poll/",
        EDI999ImportPollAPIView.as_view(),
        name="edi-999-import-poll",
    ),
    path(
        "edi-999-imports/<int:pk>/",
        EDI999ImportDetailAPIView.as_view(),
        name="edi-999-import-detail",
    ),
    path(
        "sftp-credentials/",
        SFTPCredentialsListCreateAPIView.as_view(),
        name="sftp-credentials-list-create",
    ),
    path(
        "sftp-credentials/<int:pk>/",
        SFTPCredentialsDetailAPIView.as_view(),
        name="sftp-credentials-detail",
    ),
    path(
        "sftp-directories/",
        SFTPDirectoryListCreateAPIView.as_view(),
        name="sftp-directory-list-create",
    ),
    path(
        "sftp-directories/<int:pk>/",
        SFTPDirectoryDetailAPIView.as_view(),
        name="sftp-directory-detail",
    ),
]
