# Generated by Django 5.2.17 on 2026-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_merge_patient_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
