# Generated by Django 5.2.17 on 2026-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0012_edifile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edifile',
            name='status',
            field=models.CharField(blank=True, choices=[('GENERATED', 'Generated (not yet sent)'), ('UPLOAD_QUEUED', 'Upload queued'), ('UPLOADED', 'Uploaded to SFTP (not yet confirmed by HCPF)'), ('ACKNOWLEDGED', 'Acknowledged by HCPF gateway'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='GENERATED', max_length=32, null=True),
        ),
    ]
