# Generated by Django 5.2.17 on 2026-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_service_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimserviceline',
            name='modifier_1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='claimserviceline',
            name='modifier_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='claimserviceline',
            name='modifier_3',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='claimserviceline',
            name='modifier_4',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
